version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: to-do-task-web-application-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dushan15939#
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: to-do-task-web-application-backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Dushan15939#
      DB_NAME: tododb
      DB_PORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: to-do-task-web-application-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data:
